const portfolioStyles = String.raw`
:root { --ink:#10211d; --paper:#f4f0e8; --line:rgba(16,33,29,.18); --acid:#d7fa65; --coral:#fa7562; --violet:#a47cf6; --serif: Georgia, "Times New Roman", "Noto Serif SC", serif; }
* { box-sizing:border-box; }
html { scroll-behavior:smooth; }
body { margin:0; background:var(--paper); color:var(--ink); font-family:Arial, "PingFang SC", "Microsoft YaHei", sans-serif; }
a { color:inherit; text-decoration:none; }
.shell { width:min(1260px, calc(100% - 80px)); margin:0 auto; }
.hero { min-height:100svh; background:#10211d; color:#edf4de; position:relative; overflow:hidden; isolation:isolate; display:flex; flex-direction:column; }
.grain { position:absolute; inset:0; opacity:.18; pointer-events:none; z-index:-1; background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 160 160' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.8' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.4'/%3E%3C/svg%3E"); }
.hero-orbit { position:absolute; border:1px solid rgba(215,250,101,.19); border-radius:50%; z-index:-1; }
.orbit-a { width:80vw; height:80vw; right:-22vw; bottom:-48vw; }
.orbit-b { width:44vw; height:44vw; right:7vw; bottom:-21vw; border-color:rgba(237,244,222,.12); }
.nav { height:106px; border-bottom:1px solid rgba(237,244,222,.18); display:flex; align-items:center; justify-content:space-between; }
.brand { display:flex; align-items:center; font-size:11px; letter-spacing:.13em; font-weight:700; gap:9px; }.brand span { width:35px; height:35px; display:grid; place-items:center; border:1px solid var(--acid); color:var(--acid); font-size:10px; }.brand i{height:1px;width:22px;background:rgba(237,244,222,.45)}
.nav-links{display:flex;align-items:center;gap:28px;font-size:11px;letter-spacing:.12em;text-transform:uppercase}.nav-links>a:not(.nav-contact){opacity:.7}.nav-contact{border:1px solid rgba(237,244,222,.35);padding:11px 15px}.nav-contact b,.text-link b{color:var(--acid);margin-left:6px}
.hero-content{padding:clamp(90px,15vh,174px) 0 85px;flex:1;display:flex;flex-direction:column;justify-content:center}.eyebrow{font-size:10px;letter-spacing:.17em;display:flex;align-items:center;gap:8px;color:#b3c3ae}.pulse{width:7px;height:7px;background:var(--acid);border-radius:50%;box-shadow:0 0 0 7px rgba(215,250,101,.1)}.hero-kicker{font-size:clamp(10px,1vw,13px);letter-spacing:.4em;color:var(--acid);margin:43px 0 15px}.hero h1{font-family:var(--serif);font-weight:400;font-size:clamp(58px,9.2vw,148px);line-height:.84;letter-spacing:-.075em;margin:0;max-width:900px}.hero h1 em,.statement h2 em,.contact h2 em{color:var(--acid);font-style:italic;font-weight:400}.hero-bottom{display:flex;justify-content:space-between;align-items:end;margin-top:clamp(58px,11vh,122px);max-width:730px}.hero-bottom p{font-size:14px;line-height:1.75;margin:0;color:#c2cbbd}.hero-bottom strong{color:#eff6dc;font-weight:600}.round-link{width:62px;height:62px;display:grid;place-items:center;border:1px solid rgba(237,244,222,.45);border-radius:50%;font-size:26px;transition:.25s}.round-link:hover{background:var(--acid);color:var(--ink);transform:translateY(4px)}.hero-index{position:absolute;right:30px;top:50%;transform:rotate(90deg) translateY(-50%);transform-origin:right top;display:flex;gap:10px;align-items:center;font-size:9px;letter-spacing:.17em;color:rgba(237,244,222,.5)}.hero-index div{height:1px;width:54px;background:rgba(237,244,222,.38)}.hero-foot{border-top:1px solid rgba(237,244,222,.18);padding:18px 0;display:flex;justify-content:space-between;font-size:9px;letter-spacing:.16em;color:#a6b2a3}
.statement{padding:145px 0 165px}.section-label{font-size:11px;letter-spacing:.17em;font-weight:700;text-transform:uppercase;margin:0;color:#597067}.section-label.light{color:var(--acid)}.statement-grid{display:grid;grid-template-columns:1.15fr .65fr;gap:clamp(40px,9vw,150px);margin-top:42px}.statement h2,.contact h2{font-family:var(--serif);font-size:clamp(47px,6vw,92px);line-height:.92;letter-spacing:-.065em;margin:0;font-weight:400}.statement h2 em{color:#da5f50}.statement-copy{padding-top:18px}.statement-copy p{font-size:17px;line-height:1.8;margin:0 0 22px;color:#47554e}.text-link{display:inline-block;margin-top:28px;border-bottom:1px solid var(--ink);padding-bottom:6px;font-size:12px;font-weight:700;letter-spacing:.08em}
.project-section{background:#10211d;color:#edf4de;padding:30px 0 0}.projects-head{display:flex;justify-content:space-between;align-items:end;padding-bottom:50px}.projects-head>p:last-child{font-size:12px;color:#a8b7a5;max-width:310px;line-height:1.7;margin:0}.projects{border-top:1px solid rgba(237,244,222,.23)}.project{min-height:520px;padding:24px max(40px,calc((100vw - 1260px)/2));border-bottom:1px solid rgba(237,244,222,.23);display:grid;grid-template-columns:1fr 1.35fr;grid-template-rows:auto 1fr auto;column-gap:7vw;position:relative;overflow:hidden}.project-top,.project-bottom{grid-column:1/-1;display:flex;justify-content:space-between;font-size:10px;letter-spacing:.13em;color:#b4c1af}.project-top{position:relative;z-index:2}.project-art{grid-row:2;align-self:center;position:relative;height:250px;max-width:450px;background:linear-gradient(125deg,rgba(237,244,222,.06),transparent 48%);border:1px solid rgba(237,244,222,.13);overflow:hidden}.project-art:before,.project-art:after{content:"";position:absolute;border:1px solid currentColor;opacity:.6;border-radius:50%}.project-art:before{width:280px;height:280px;left:-90px;bottom:-155px}.project-art:after{width:160px;height:160px;right:-35px;top:-40px}.project-coral .project-art{color:var(--coral)}.project-violet .project-art{color:var(--violet)}.project-lime .project-art{color:var(--acid)}.art-window{position:absolute;inset:44px 45px 37px 53px;border:1px solid rgba(237,244,222,.37);background:rgba(14,32,28,.7);transform:rotate(-4deg);padding:13px}.art-dots{display:flex;gap:5px}.art-dots i{width:5px;height:5px;border-radius:50%;background:currentColor}.art-lines{margin:32px 0 0 12px;display:grid;gap:9px}.art-lines b{height:4px;background:rgba(237,244,222,.35);display:block}.art-lines b:nth-child(1){width:57%}.art-lines b:nth-child(2){width:75%}.art-lines b:nth-child(3){width:38%}.art-lines b:nth-child(4){width:67%}.art-node{position:absolute;width:14px;height:14px;background:currentColor;border-radius:50%;box-shadow:0 0 0 7px rgba(237,244,222,.04)}.n1{left:30px;top:38px}.n2{right:57px;bottom:28px}.n3{right:27%;top:29px}.project-copy{align-self:center;position:relative;z-index:1}.project-copy h3{font-family:var(--serif);font-weight:400;font-size:clamp(35px,4vw,63px);line-height:.96;letter-spacing:-.065em;margin:0 0 21px}.project-copy>p{font-size:15px;line-height:1.75;color:#b7c3b2;max-width:465px;margin:0}.tag-row{display:flex;flex-wrap:wrap;gap:8px;margin-top:25px}.tag-row span{border:1px solid rgba(237,244,222,.32);padding:7px 9px;font-size:10px;letter-spacing:.06em}.project-bottom{align-self:end;padding-top:28px}.project-bottom span{color:#849483;max-width:57%}.project-bottom a{font-weight:700;color:var(--acid)}.project-bottom b{font-size:17px;margin-left:7px}
.capabilities{padding:145px 0 155px}.cap-title{display:flex;justify-content:space-between;align-items:start;border-bottom:1px solid var(--line);padding-bottom:24px}.cap-title>p:last-child{max-width:280px;line-height:1.7;font-size:13px;margin:0;color:#5d6b64}.cap-list{display:grid;grid-template-columns:repeat(3,1fr)}.cap-list article{padding:32px 28px 0 0;min-height:230px;border-right:1px solid var(--line);padding-left:24px}.cap-list article:first-child{padding-left:0}.cap-list article:last-child{border:0}.cap-list span{font-size:11px;color:#cf5e52;font-weight:700}.cap-list h3{font-family:var(--serif);font-weight:400;font-size:32px;letter-spacing:-.05em;margin:47px 0 10px}.cap-list p{color:#5d6b64;font-size:14px;line-height:1.7;margin:0;max-width:260px}
.contact{background:var(--acid);color:var(--ink);padding:30px 0 22px}.contact h2{margin:66px 0 68px}.contact h2 em{color:#cf5d4e}.contact-grid{display:grid;grid-template-columns:1fr 1fr;border-top:1px solid rgba(16,33,29,.3)}.contact-grid a{display:grid;grid-template-columns:auto 1fr auto;gap:25px;align-items:center;border-bottom:1px solid rgba(16,33,29,.3);padding:22px 0}.contact-grid a:first-child{border-right:1px solid rgba(16,33,29,.3);padding-right:35px}.contact-grid a:last-child{padding-left:35px}.contact-grid span{font-size:10px;letter-spacing:.13em}.contact-grid b{font-family:var(--serif);font-size:19px;font-weight:400}.contact-grid i{font-style:normal;font-size:24px}.contact-foot{display:flex;justify-content:space-between;margin-top:70px;font-size:9px;letter-spacing:.14em}
@media (max-width:700px){.shell{width:min(100% - 40px,1260px)}.nav{height:76px}.nav-links>a:not(.nav-contact){display:none}.nav-links{gap:0}.hero-content{padding:88px 0 50px}.hero h1{font-size:clamp(54px,16vw,82px)}.hero-index{display:none}.hero-foot{font-size:8px}.hero-bottom p{font-size:12px}.round-link{width:52px;height:52px}.statement{padding:88px 0}.statement-grid{grid-template-columns:1fr;gap:28px}.statement-copy{padding:0}.statement-copy p{font-size:15px}.projects-head{display:block;padding-bottom:28px}.projects-head>p:last-child{margin-top:19px}.project{padding:20px;min-height:560px;display:flex;flex-direction:column;gap:25px}.project-top{order:0}.project-art{order:1;min-height:190px;width:100%;height:190px}.project-copy{order:2}.project-copy h3{font-size:42px}.project-bottom{order:3;margin-top:auto;align-items:end}.project-bottom span{font-size:8px;line-height:1.5}.capabilities{padding:88px 0}.cap-title{display:block}.cap-title>p:last-child{margin-top:20px}.cap-list{display:block}.cap-list article,.cap-list article:first-child{min-height:0;padding:28px 0;border-right:0;border-bottom:1px solid var(--line)}.cap-list h3{margin:26px 0 10px}.contact h2{margin:52px 0}.contact-grid{grid-template-columns:1fr}.contact-grid a:first-child,.contact-grid a:last-child{border-right:0;padding:20px 0}.contact-grid b{font-size:16px}.contact-foot{margin-top:45px;font-size:7px}.contact-foot span:last-child{display:none}}

/* v2: distinct project stories, evidence links, and lightweight motion */
@keyframes rise-in { from { opacity:0; transform:translateY(20px); } to { opacity:1; transform:translateY(0); } }
@keyframes float-orbit { 50% { transform:translate3d(0,-14px,0) rotate(2deg); } }
@keyframes travel { to { transform:translateX(-50%); } }
@keyframes blink { 50% { opacity:.35; } }
.hero-content > * { animation:rise-in .8s both cubic-bezier(.2,.75,.2,1); }
.hero-content > :nth-child(1) { animation-delay:.05s; }.hero-content > :nth-child(2) { animation-delay:.12s; }.hero-content > :nth-child(3) { animation-delay:.2s; }.hero-content > :nth-child(4) { animation-delay:.3s; }
.hero-orbit { animation:float-orbit 10s ease-in-out infinite; }.orbit-b { animation-delay:-5s; }
.signal-strip { overflow:hidden; background:#cf5f51; color:#10211d; white-space:nowrap; font-size:11px; font-weight:700; letter-spacing:.13em; padding:14px 0; }.signal-strip>div { display:inline-block; min-width:max-content; animation:travel 26s linear infinite; }.signal-strip i { font-style:normal; margin:0 20px; }
.commerce-visual,.ticket-visual,.flow-visual { grid-row:2; align-self:center; position:relative; height:250px; max-width:450px; overflow:hidden; border:1px solid rgba(237,244,222,.15); background:rgba(237,244,222,.035); transition:transform .45s cubic-bezier(.2,.8,.2,1), border-color .3s; }.project:hover .commerce-visual,.project:hover .ticket-visual,.project:hover .flow-visual { transform:translateY(-8px) rotate(-1deg); border-color:rgba(237,244,222,.48); }
.commerce-visual { padding:19px; color:#ff806c; background:linear-gradient(135deg,rgba(250,117,98,.14),transparent 58%),rgba(237,244,222,.03); }.commerce-top{display:flex;justify-content:space-between;font-size:9px;letter-spacing:.14em;color:#ffc5bc}.commerce-lanes{height:77px;margin:24px 0 20px;display:grid;gap:9px}.commerce-lanes i{border:1px solid rgba(250,117,98,.6);position:relative}.commerce-lanes i:after{content:"";position:absolute;right:16%;top:-1px;width:8px;height:8px;border-radius:50%;background:#ff806c;box-shadow:0 0 0 7px rgba(250,117,98,.14)}.commerce-skus{display:flex;gap:8px}.commerce-skus b{font-size:10px;letter-spacing:.08em;border:1px solid rgba(250,117,98,.45);padding:8px}.commerce-order{position:absolute;right:19px;bottom:18px;font-family:var(--serif);font-size:29px;letter-spacing:-.04em}.commerce-order em{font-style:normal;color:var(--acid)}
.ticket-visual { color:#a882f5; background:radial-gradient(circle at 24% 26%,rgba(164,124,246,.2),transparent 18%),rgba(237,244,222,.03); padding:22px; }.ticket-chip{border:1px solid rgba(164,124,246,.7);display:inline-block;padding:7px 10px;font-size:10px;letter-spacing:.1em}.ticket-rail{position:absolute;left:42px;top:75px;bottom:27px;width:1px;background:rgba(164,124,246,.4);display:grid;align-content:space-between}.ticket-rail i{width:9px;height:9px;border-radius:50%;background:#a882f5;transform:translateX(-4px);box-shadow:0 0 0 7px rgba(164,124,246,.1)}.ticket-card{position:absolute;left:67px;padding:11px 14px;border:1px solid rgba(237,244,222,.28);font-size:10px;letter-spacing:.12em;background:#11241f}.card-a{top:72px;right:42px;transform:rotate(-4deg)}.card-b{top:125px;right:71px;transform:rotate(3deg)}.card-c{top:178px;right:28px;transform:rotate(-2deg)}
.flow-visual { color:#d7fa65; padding:22px; background:linear-gradient(110deg,rgba(215,250,101,.12),transparent 50%),rgba(237,244,222,.03); }.flow-head{font-size:10px;letter-spacing:.14em}.flow-steps{position:absolute;left:22px;right:22px;top:87px;display:flex;align-items:center;justify-content:space-between}.flow-steps b{width:88px;height:88px;border:1px solid rgba(215,250,101,.7);display:flex;flex-direction:column;justify-content:center;padding:12px;font-size:20px;font-family:var(--serif);font-weight:400}.flow-steps b span{font-family:Arial,"Microsoft YaHei",sans-serif;font-size:8px;letter-spacing:.12em;margin-top:8px}.flow-steps i{font-style:normal;font-size:18px;color:rgba(215,250,101,.7)}.flow-log{position:absolute;bottom:20px;left:22px;right:22px;display:flex;justify-content:space-between;font-family:monospace;font-size:9px;color:#d7fa65}.flow-log span:last-child{animation:blink 1.8s infinite}
.project-lens{font-size:10px!important;letter-spacing:.13em;text-transform:uppercase;color:var(--acid)!important;margin:0 0 16px!important}.project-links{display:flex;gap:20px;margin-top:25px}.project-links a{font-size:10px;letter-spacing:.1em;border-bottom:1px solid rgba(237,244,222,.45);padding-bottom:5px;transition:color .2s,border-color .2s}.project-links a:hover{color:var(--acid);border-color:var(--acid)}
@media (max-width:700px){.signal-strip{font-size:9px}.commerce-visual,.ticket-visual,.flow-visual{order:1;grid-row:auto;min-height:190px;width:100%;height:190px}.project-copy{order:2}.commerce-lanes{height:42px;margin:16px 0}.commerce-order{font-size:21px}.card-a{top:52px}.card-b{top:95px}.card-c{top:138px}.ticket-rail{top:54px;bottom:19px}.flow-steps{top:52px}.flow-steps b{width:65px;height:65px;font-size:16px}.flow-log{bottom:13px}.project-links{margin-top:17px;gap:13px}}
@media (prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.01ms!important;animation-iteration-count:1!important;scroll-behavior:auto!important}}

`;

export default portfolioStyles;

